apiVersion: v1
kind: Pod
metadata:
  name: multiple
spec:
  containers:
  - image: nginx
    name: nginx
  - image: almalinux
    name: sidecar
    command: ["sleep", "200"]

# Here ekctl create a pod with 2 containers and both of them has the same ip address
