apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  spot: true
  ssh:
    publicKeyName: kubernetes #place your key

# Create cluster
[ec2-user@ip-172-31-86-12 ~]$ eksctl create cluster --config-file=eks-config.yaml
