apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot-cluster-1
    instanceType: t3.medium  # Specify the instance type
    spot: true
    desiredCapacity: 2  # You can define the number of instances if needed
    ssh:
      publicKeyName: docker-key
